# Project: biTree
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = ../Queue/SqQueue.o ../Stack/SqStack.o ../biTree/biTree.o main.o ../Queue/LinkQueue.o
LINKOBJ  = ../Queue/SqQueue.o ../Stack/SqStack.o ../biTree/biTree.o main.o ../Queue/LinkQueue.o
LIBS     = -L"D:/Dev-cpp/MinGW64/lib" -L"D:/Dev-cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Dev-cpp/MinGW64/include" -I"D:/Dev-cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-cpp/MinGW64/include" -I"D:/Dev-cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = biTree.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../Queue/SqQueue.o: ../Queue/SqQueue.cpp
	$(CPP) -c ../Queue/SqQueue.cpp -o ../Queue/SqQueue.o $(CXXFLAGS)

../Stack/SqStack.o: ../Stack/SqStack.cpp
	$(CPP) -c ../Stack/SqStack.cpp -o ../Stack/SqStack.o $(CXXFLAGS)

../biTree/biTree.o: ../biTree/biTree.cpp
	$(CPP) -c ../biTree/biTree.cpp -o ../biTree/biTree.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

../Queue/LinkQueue.o: ../Queue/LinkQueue.cpp
	$(CPP) -c ../Queue/LinkQueue.cpp -o ../Queue/LinkQueue.o $(CXXFLAGS)
